#pragma once

#include <unordered_map>
#include <string>

enum class Genre {
	Dystopian,
	ScienceFiction,
	Fantasy,
	Adventure,
	History,
	LiteraryFiction,
	HistoricalFiction,
	Mystery,
	Thriller,
	Romance,
	Horror,
	YoungAdult,
	ChildrensLiterature,
	GraphicNovel,
	MagicalRealism,
	ChickLit,
	NewAdult,
	PostApocalyptic,
	Western,
	CrimeFiction,
	LiteraryMistery,
	Biography,
	Memoir,
	SelfHelp,
	TrueCrime,
	TravelWriting,
	Cookbook,
	Essay,
	Science,
	Politics,
	Philosophy,
	HealthAndWellness,
	Business,
	Parenting,
	NatureWriting,
	Spirituality,
	Sociology,
	Psychology,
	Education,
	Finance,
	FanFiction,
	ClassicLiterature,
	Romanticism,
	Realism,
	Modernism,
	Surrealism,
	GothicFiction,
	VictorianLiterature,
	BeatGeneration,
	Existentialism,
	HistoricalRomance,
	CozyMystery,
	UrbanFantasy,
	HorrorComedy,
	ShortStories,
	Poetry,
	Journals,
	Action,
	DarkFantasy,
	CozyFantasy,
	Nature

};

inline std::string genreToString(Genre genre) {
    static const std::unordered_map<Genre, std::string> genreMap = {
        {Genre::Dystopian, "Dystopian"},
        {Genre::ScienceFiction, "Science Fiction"},
        {Genre::Fantasy, "Fantasy"},
        {Genre::Adventure, "Adventure"},
        {Genre::History, "History"},
        {Genre::LiteraryFiction, "Literary Fiction"},
        {Genre::HistoricalFiction, "Historical Fiction"},
        {Genre::Mystery, "Mystery"},
        {Genre::Thriller, "Thriller"},
        {Genre::Romance, "Romance"},
        {Genre::Horror, "Horror"},
        {Genre::YoungAdult, "Young Adult"},
        {Genre::ChildrensLiterature, "Children's Literature"},
        {Genre::GraphicNovel, "Graphic Novel"},
        {Genre::MagicalRealism, "Magical Realism"},
        {Genre::ChickLit, "Chick Lit"},
        {Genre::NewAdult, "New Adult"},
        {Genre::PostApocalyptic, "Post Apocalyptic"},
        {Genre::Western, "Western"},
        {Genre::CrimeFiction, "Crime Fiction"},
        {Genre::LiteraryMistery, "Literary Mystery"},
        {Genre::Biography, "Biography"},
        {Genre::Memoir, "Memoir"},
        {Genre::SelfHelp, "Self Help"},
        {Genre::TrueCrime, "True Crime"},
        {Genre::TravelWriting, "Travel Writing"},
        {Genre::Cookbook, "Cookbook"},
        {Genre::Essay, "Essay"},
        {Genre::Science, "Science"},
        {Genre::Politics, "Politics"},
        {Genre::Philosophy, "Philosophy"},
        {Genre::HealthAndWellness, "Health and Wellness"},
        {Genre::Business, "Business"},
        {Genre::Parenting, "Parenting"},
        {Genre::NatureWriting, "Nature Writing"},
        {Genre::Spirituality, "Spirituality"},
        {Genre::Sociology, "Sociology"},
        {Genre::Psychology, "Psychology"},
        {Genre::Education, "Education"},
        {Genre::Finance, "Finance"},
        {Genre::FanFiction, "Fan Fiction"},
        {Genre::ClassicLiterature, "Classic Literature"},
        {Genre::Romanticism, "Romanticism"},
        {Genre::Realism, "Realism"},
        {Genre::Modernism, "Modernism"},
        {Genre::Surrealism, "Surrealism"},
        {Genre::GothicFiction, "Gothic Fiction"},
        {Genre::VictorianLiterature, "Victorian Literature"},
        {Genre::BeatGeneration, "Beat Generation"},
        {Genre::Existentialism, "Existentialism"},
        {Genre::HistoricalRomance, "Historical Romance"},
        {Genre::CozyMystery, "Cozy Mystery"},
        {Genre::UrbanFantasy, "Urban Fantasy"},
        {Genre::HorrorComedy, "Horror Comedy"},
        {Genre::ShortStories, "Short Stories"},
        {Genre::Poetry, "Poetry"},
        {Genre::Journals, "Journals"},
        {Genre::Action, "Action"},
        {Genre::DarkFantasy, "Dark Fantasy"},
        {Genre::CozyFantasy, "Cozy Fantasy"},
        {Genre::Nature, "Nature"}
    };

    auto it = genreMap.find(genre);
    if (it != genreMap.end()) {
        return it->second;
    }
    return "Unknown Genre";
}
